<a href="https://colab.research.google.com/github/comb0601/codingtest/blob/main/deepfake.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [73]:
import os
import glob
import cv2
import numpy as np

In [92]:
#TEST_PATH = '/content/'
TRAIN_PATH = '/content/sample_data/'

#metadata = '../input/deepfake-detection-challenge/train_sample_videos/metadata.json'

In [93]:
# load the filenames for train videos
train_fns = sorted(glob.glob(TRAIN_PATH + '*.mp4'))

# load the filenames for test videos
#test_fns = sorted(glob.glob(TEST_PATH + '*.mp4'))

print('There are {} samples in the train set.'.format(len(train_fns)))
#print('There are {} samples in the test set.'.format(len(test_fns)))

There are 1 samples in the train set.


In [94]:
def get_frames(filename):
    '''
    Get all frames from the video
    INPUT:
        filename - video filename
    OUTPUT:
        frames - the array of video frames
    '''
    frames = []
    cap = cv2.VideoCapture(filename)

    #while(cap.isOpened()):
    while len(frames) < 50 :
        ret, frame = cap.read()
                
        if not ret:
            break;
            
        image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        frames.append(image)

    cap.release()
    cv2.destroyAllWindows()
    return frames



In [95]:
frames = get_frames(train_fns[0])


In [96]:
np.shape(frames)

(50, 1080, 1920, 3)

In [36]:
!pip install mtcnn
!pip install facenet-pytorch

In [79]:
from facenet_pytorch import MTCNN
import cv2
from PIL import Image
import numpy as np
from matplotlib import pyplot as plt


In [80]:
# Create face detector
mtcnn = MTCNN(keep_all=True, post_process=False)



In [97]:
faces = mtcnn(frames)


KeyboardInterrupt: ignored

In [ ]:
np.shape(faces[0])

In [98]:
save_paths = [f'image_{i}.jpg' for i in range(len(frames))]
#for i in range(len(faces)):
mtcnn(frames, save_path=save_paths)

[tensor([[[[165., 165., 165.,  ...,  41.,  43.,  45.],
           [165., 165., 165.,  ...,  40.,  43.,  46.],
           [167., 167., 167.,  ...,  40.,  43.,  47.],
           ...,
           [163., 163., 162.,  ..., 115., 115., 113.],
           [163., 162., 161.,  ..., 117., 117., 115.],
           [161., 161., 160.,  ..., 117., 116., 116.]],
 
          [[158., 158., 158.,  ...,  35.,  37.,  39.],
           [158., 158., 158.,  ...,  34.,  37.,  40.],
           [158., 158., 158.,  ...,  34.,  37.,  41.],
           ...,
           [153., 153., 152.,  ...,  85.,  85.,  85.],
           [153., 153., 152.,  ...,  87.,  87.,  86.],
           [153., 153., 152.,  ...,  87.,  86.,  85.]],
 
          [[131., 131., 131.,  ...,  30.,  32.,  34.],
           [131., 131., 131.,  ...,  29.,  32.,  35.],
           [131., 130., 129.,  ...,  29.,  32.,  34.],
           ...,
           [131., 131., 130.,  ...,  59.,  59.,  58.],
           [131., 131., 130.,  ...,  61.,  61.,  60.],
           

In [48]:

import numpy as np
import cv2
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

In [49]:
for face in faces:
  image = 


ValueError: ignored

In [101]:
output = open('result_org.csv', 'w')
output.write('r,g,b\n')

for i in range(len(frames)) :
  image = cv2.imread('/content/image_' + str(i) + '.jpg')
  image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) #RGB 형태로 변환
  image = image.reshape((image.shape[0] * image.shape[1], 3))
  k = 1 
  clt = KMeans(n_clusters = k)
  clt.fit(image)
  for center in clt.cluster_centers_:
    print(center)
    output.write(str(center[0]) + ',' + str(center[1]) + ',' + str(center[2]) + '\n')

[139.18914062 104.82214844  81.91105469]
[135.305625   100.61226562  78.64742187]
[132.57773437  98.8459375   76.54855469]
[132.14058594  98.32140625  76.51457031]
[130.74964844  97.64273438  75.8340625 ]
[134.90988281 101.47363281  79.56488281]
[134.23011719 101.12675781  78.61636719]
[129.71980469  96.73445313  75.36832031]
[128.34386719  96.48679688  74.81726562]
[128.80839844  96.5965625   75.3446875 ]
[129.50519531  97.66222656  75.67003906]
[132.75167969 100.28742187  78.55972656]
[133.375      100.73851563  78.54742187]
[134.51828125 101.14636719  79.2653125 ]
[135.03382812 101.75144531  79.25375   ]
[137.61019531 104.37128906  81.94390625]
[135.35148437 102.48082031  80.17320313]
[135.24824219 102.15472656  80.09496094]
[135.24390625 102.40265625  79.64867188]
[136.40214844 103.89214844  81.85351562]
[137.9259375  104.40988281  82.07195312]
[134.60167969 102.210625    80.271875  ]
[134.11578125 101.98089844  79.49582031]
[136.70421875 104.14304688  82.01679687]
[137.62179688 10

In [69]:
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) #RGB 형태로 변환
print(image.shape)
image2 = cv2.cvtColor(image, cv2.COLOR_BGR2HSV) #HSV 형태로 변환
print(image2.shape)

(1, 3, 3)
(1, 3, 3)


In [63]:
image

array([[[2.4000000e+02, 7.6643538e-29, 9.1366217e-36],
        [          nan, 0.0000000e+00, 0.0000000e+00],
        [2.4369162e+02, 9.9999565e-01, 8.2759366e+08]]], dtype=float32)

In [ ]:

#plt.imshow(image) #424000,3
plt.imshow(image2)#141000, 3, 3

In [ ]:
#image = image.reshape((image.shape[0] * image.shape[1], 3))
image2 = image2.reshape((image2.shape[0] * image2.shape[1], 3))
print(image2.shape)
k = 1 
clt = KMeans(n_clusters = k)
clt.fit(image2)


In [ ]:
for center in clt.cluster_centers_:
    print(center)

In [ ]:
def centroid_histogram(clt):
    # grab the number of different clusters and create a histogram
    # based on the number of pixels assigned to each cluster
    numLabels = np.arange(0, len(np.unique(clt.labels_)) + 1)
    (hist, _) = np.histogram(clt.labels_, bins=numLabels)

    # normalize the histogram, such that it sums to one
    hist = hist.astype("float")
    hist /= hist.sum()

    # return the histogram
    return hist


hist = centroid_histogram(clt)
print(hist)

In [ ]:
def plot_colors(hist, centroids):
    # initialize the bar chart representing the relative frequency
    # of each of the colors
    bar = np.zeros((50, 300, 3), dtype="uint8")
    startX = 0

    # loop over the percentage of each cluster and the color of
    # each cluster
    for (percent, color) in zip(hist, centroids):
        # plot the relative percentage of each cluster
        endX = startX + (percent * 300)
        cv2.rectangle(bar, (int(startX), 0), (int(endX), 50),
                      color.astype("uint8").tolist(), -1)
        startX = endX

    # return the bar chart
    return bar

bar = plot_colors(hist, clt.cluster_centers_)


# show our color bart
plt.figure()
plt.axis("off")
plt.imshow(bar)
plt.show()