<a href="https://colab.research.google.com/github/comb0601/codingtest/blob/main/deepfake.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
import glob
import cv2
import numpy as np

In [16]:
#TEST_PATH = '/content/'
TRAIN_PATH = '/content/'

#metadata = '../input/deepfake-detection-challenge/train_sample_videos/metadata.json'

In [17]:
# load the filenames for train videos
train_fns = sorted(glob.glob(TRAIN_PATH + '*.mp4'))

# load the filenames for test videos
#test_fns = sorted(glob.glob(TEST_PATH + '*.mp4'))

print('There are {} samples in the train set.'.format(len(train_fns)))
#print('There are {} samples in the test set.'.format(len(test_fns)))

There are 2 samples in the train set.


In [18]:
def get_frames(filename):
    '''
    Get all frames from the video
    INPUT:
        filename - video filename
    OUTPUT:
        frames - the array of video frames
    '''
    frames = []
    cap = cv2.VideoCapture(filename)

    #while(cap.isOpened()):
    while len(frames) < 60 :
        ret, frame = cap.read()
                
        if not ret:
            break;
            
        image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        frames.append(image)

    cap.release()
    cv2.destroyAllWindows()
    return frames



In [19]:
frames = get_frames(train_fns[0])


In [20]:
np.shape(frames)

(60, 1080, 1920, 3)

In [7]:
!pip install mtcnn
!pip install facenet-pytorch

In [8]:
from facenet_pytorch import MTCNN
import cv2
from PIL import Image
import numpy as np
from matplotlib import pyplot as plt


In [9]:
# Create face detector
mtcnn = MTCNN(keep_all=True, post_process=False)



In [10]:
faces = mtcnn(frames)


In [15]:
save_paths = [f'image_{i}.jpg' for i in range(len(frames))]
#for i in range(len(faces)):
mtcnn(frames, save_path=save_paths)

[tensor([[[[116., 118., 120.,  ...,  48.,  50.,  52.],
           [117., 119., 121.,  ...,  45.,  48.,  50.],
           [119., 120., 120.,  ...,  44.,  47.,  50.],
           ...,
           [ 35.,  49.,  60.,  ..., 160., 161., 163.],
           [ 35.,  49.,  60.,  ..., 162., 165., 166.],
           [ 35.,  49.,  60.,  ..., 163., 165., 167.]],
 
          [[106., 108., 110.,  ...,  38.,  40.,  42.],
           [108., 110., 112.,  ...,  37.,  40.,  43.],
           [110., 111., 111.,  ...,  37.,  40.,  44.],
           ...,
           [ 25.,  33.,  42.,  ..., 133., 133., 135.],
           [ 25.,  33.,  42.,  ..., 135., 137., 138.],
           [ 25.,  33.,  42.,  ..., 136., 137., 139.]],
 
          [[ 94.,  96.,  98.,  ...,  37.,  39.,  41.],
           [ 94.,  96.,  97.,  ...,  36.,  38.,  39.],
           [ 94.,  95.,  95.,  ...,  36.,  38.,  39.],
           ...,
           [ 21.,  27.,  36.,  ..., 107., 106., 106.],
           [ 21.,  27.,  36.,  ..., 109., 110., 109.],
           

In [23]:

import numpy as np
import cv2
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

In [49]:
for face in faces:
  image = 


ValueError: ignored

In [24]:
output = open('result_org.csv', 'w')
output.write('r,g,b\n')

for i in range(len(frames)) :
  image = cv2.imread('/content/image_' + str(i) + '.jpg')
  image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) #RGB 형태로 변환
  image = image.reshape((image.shape[0] * image.shape[1], 3))
  k = 1 
  clt = KMeans(n_clusters = k)
  clt.fit(image)
  for center in clt.cluster_centers_:
    print(center)
    output.write(str(center[0]) + ',' + str(center[1]) + ',' + str(center[2]) + '\n')

[137.82507813 106.61425781  93.32914062]
[137.40074219 106.27285156  93.06394531]
[141.09722656 108.8134375   95.65824219]
[136.21628906 105.25730469  92.47960938]
[140.82394531 108.77253906  95.39316406]
[140.15667969 108.32390625  94.97910156]
[142.20410156 109.97691406  96.51320313]
[140.96058594 109.20640625  96.18253906]
[140.3096875  108.41433594  95.43085937]
[141.10753906 109.18402344  96.32363281]
[138.60609375 106.70507812  94.61792969]
[141.06875    109.31363281  96.72246094]
[140.08039063 108.34933594  95.74710937]
[141.58636719 109.0134375   96.78699219]
[141.05273438 109.16980469  96.72789063]
[138.68550781 107.12675781  95.2903125 ]
[140.09601563 108.24542969  95.86894531]
[139.95902344 108.78625     96.2325    ]
[140.34425781 108.93980469  96.57148437]
[138.38410156 107.27191406  95.01546875]
[138.02628906 107.10972656  95.18375   ]
[139.22328125 108.09320313  95.731875  ]
[138.73863281 107.96945313  95.7453125 ]
[138.26398438 107.49167969  94.94015625]
[137.740625   10

In [69]:
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) #RGB 형태로 변환
print(image.shape)
image2 = cv2.cvtColor(image, cv2.COLOR_BGR2HSV) #HSV 형태로 변환
print(image2.shape)

(1, 3, 3)
(1, 3, 3)


In [63]:
image

array([[[2.4000000e+02, 7.6643538e-29, 9.1366217e-36],
        [          nan, 0.0000000e+00, 0.0000000e+00],
        [2.4369162e+02, 9.9999565e-01, 8.2759366e+08]]], dtype=float32)

In [ ]:

#plt.imshow(image) #424000,3
plt.imshow(image2)#141000, 3, 3

In [ ]:
#image = image.reshape((image.shape[0] * image.shape[1], 3))
image2 = image2.reshape((image2.shape[0] * image2.shape[1], 3))
print(image2.shape)
k = 1 
clt = KMeans(n_clusters = k)
clt.fit(image2)


In [ ]:
for center in clt.cluster_centers_:
    print(center)

In [ ]:
def centroid_histogram(clt):
    # grab the number of different clusters and create a histogram
    # based on the number of pixels assigned to each cluster
    numLabels = np.arange(0, len(np.unique(clt.labels_)) + 1)
    (hist, _) = np.histogram(clt.labels_, bins=numLabels)

    # normalize the histogram, such that it sums to one
    hist = hist.astype("float")
    hist /= hist.sum()

    # return the histogram
    return hist


hist = centroid_histogram(clt)
print(hist)

In [ ]:
def plot_colors(hist, centroids):
    # initialize the bar chart representing the relative frequency
    # of each of the colors
    bar = np.zeros((50, 300, 3), dtype="uint8")
    startX = 0

    # loop over the percentage of each cluster and the color of
    # each cluster
    for (percent, color) in zip(hist, centroids):
        # plot the relative percentage of each cluster
        endX = startX + (percent * 300)
        cv2.rectangle(bar, (int(startX), 0), (int(endX), 50),
                      color.astype("uint8").tolist(), -1)
        startX = endX

    # return the bar chart
    return bar

bar = plot_colors(hist, clt.cluster_centers_)


# show our color bart
plt.figure()
plt.axis("off")
plt.imshow(bar)
plt.show()